name: CI Frontend Next.js

on:
  push:
    branches: [ main, master ]
    paths:
      - 'frontend/**' # Ne se déclenche que si on modifie le frontend

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    # On indique à GitHub que tout se passe dans le dossier frontend
    defaults:
      run:
        working-directory: ./frontend

    steps:
    - name: Récupérer le code
      uses: actions/checkout@v4

    - name: Configurer Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' # Utilise la version de Node.js de ton projet
        cache: 'npm'
        cache-dependency-path: './frontend/package-lock.json'

    - name: Installer les dépendances
      run: npm ci

    - name: Vérifier le code (Lint)
      run: npm run lint

    - name: Tester le Build
      run: npm run build
      # On passe des fausses clés juste pour que le build Next.js passe le test
      env:
        NEXT_PUBLIC_SUPABASE_URL: "https://test.supabase.co"
        NEXT_PUBLIC_SUPABASE_ANON_KEY: "test-key"